# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/thing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/thing.proto',
  package='testServer',
  syntax='proto3',
  serialized_options=_b('Z\007./proto'),
  serialized_pb=_b('\n\x11proto/thing.proto\x12\ntestServer\"\x1f\n\nDataAddReq\x12\x11\n\tbase_data\x18\x01 \x01(\x05\" \n\nDataAddRes\x12\x12\n\nanaly_data\x18\x01 \x01(\x05\x32N\n\ntestServer\x12@\n\x0e\x61naly_data_add\x12\x16.testServer.DataAddReq\x1a\x16.testServer.DataAddResB\tZ\x07./protob\x06proto3')
)




_DATAADDREQ = _descriptor.Descriptor(
  name='DataAddReq',
  full_name='testServer.DataAddReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_data', full_name='testServer.DataAddReq.base_data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=64,
)


_DATAADDRES = _descriptor.Descriptor(
  name='DataAddRes',
  full_name='testServer.DataAddRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='analy_data', full_name='testServer.DataAddRes.analy_data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['DataAddReq'] = _DATAADDREQ
DESCRIPTOR.message_types_by_name['DataAddRes'] = _DATAADDRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataAddReq = _reflection.GeneratedProtocolMessageType('DataAddReq', (_message.Message,), {
  'DESCRIPTOR' : _DATAADDREQ,
  '__module__' : 'proto.thing_pb2'
  # @@protoc_insertion_point(class_scope:testServer.DataAddReq)
  })
_sym_db.RegisterMessage(DataAddReq)

DataAddRes = _reflection.GeneratedProtocolMessageType('DataAddRes', (_message.Message,), {
  'DESCRIPTOR' : _DATAADDRES,
  '__module__' : 'proto.thing_pb2'
  # @@protoc_insertion_point(class_scope:testServer.DataAddRes)
  })
_sym_db.RegisterMessage(DataAddRes)


DESCRIPTOR._options = None

_TESTSERVER = _descriptor.ServiceDescriptor(
  name='testServer',
  full_name='testServer.testServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='analy_data_add',
    full_name='testServer.testServer.analy_data_add',
    index=0,
    containing_service=None,
    input_type=_DATAADDREQ,
    output_type=_DATAADDRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTSERVER)

DESCRIPTOR.services_by_name['testServer'] = _TESTSERVER

# @@protoc_insertion_point(module_scope)
